resources:
  - name: gitresource
    type: GitRepo
    configuration:
      gitProvider: raksha78_github
      path: raksha78/webhookWithresources
      buildOn:
         commit: true
         pullRequestCreate: true
         pullRequestClose: true
         releaseCreate: true
         tagCreate: true
pipelines:
  - name: testPipelineRel
    steps:
      - name: testStep
        type: Powershell
        configuration:
          inputResources:
            - name: gitresource
        execution:
           onStart:
            - echo "executing onStart"
           onExecute:
             - echo "executing onExecute"
             - pushd $res_gitresource_resourcePath
