pipelines:
 - name: pipeline_test
   steps:
     - name: step_1
       type: Bash
       configuration:
         inputResources:
           - name: "resource_001"
       execution:
         onExecute:
           - echo "hi"
